version: "2.4"
services:
  client:
    extends:
      file: ./client/docker-compose.yaml
      service: client
    environment:
      API_URL: "http://localhost:4000"
    links:
      - server
  server:
    extends:
      file: ./server/docker-compose.yaml
      service: server
#    inherited envs:
#      REDIS_HOST: "${REDIS_HOST}"
#      REDIS_PASSWORD: "${REDIS_PASSWORD}"
